// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9AYLoHCstTpvN-WEHIWvGNP8BeMpLSIo',
    appId: '1:422052267349:android:734c2f9651ee7e8f99dbdc',
    messagingSenderId: '422052267349',
    projectId: 'plantcareai-a1718',
    storageBucket: 'plantcareai-a1718.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_UE49zRNkp0Rq3KTlzHCO5Ju2pZ7nY4k',
    appId: '1:422052267349:ios:609ca13b586b7c5699dbdc',
    messagingSenderId: '422052267349',
    projectId: 'plantcareai-a1718',
    storageBucket: 'plantcareai-a1718.firebasestorage.app',
    iosBundleId: 'com.alaasohail.plantcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRsjsdP_1Mas-UY5FUA7juFA2iqaRUNYI',
    appId: '1:422052267349:web:5b11594f15b16c9a99dbdc',
    messagingSenderId: '422052267349',
    projectId: 'plantcareai-a1718',
    authDomain: 'plantcareai-a1718.firebaseapp.com',
    storageBucket: 'plantcareai-a1718.firebasestorage.app',
    measurementId: 'G-R8NVET3M1B',
  );
}
